project_id = "gawcojyqqfskewuxxqhm"

[functions.director-ai]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false

[functions.generate-chat-summary]
verify_jwt = false

[functions.atlas-generate-image]
verify_jwt = false

[functions.atlas-generate-video]
verify_jwt = false
